id: '4d30e050-66a9-427b-7391-08dd7ccec69f'
name: 'C3-X-DB-DV'
description: 'This is my eLearning Project with the Databricks DataVault and Mart generator to practice for the course C3-X-DB-DV'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Spark.Databricks'
  version: '1.9.2'
sourceSystems:
  - id: '9c53c850-b7ec-4bdc-a758-d8914e4b1a52'
    name: 'ADW_FI'
    isLinkedProject: true
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
  - id: '9c7289e4-5f92-4193-b646-4e2865998a97'
    name: 'CRM_FI'
    isLinkedProject: true
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
